"""empty message

Revision ID: 383a0a6dc3e4
Revises: 27f5c8109729
Create Date: 2019-02-20 15:55:12.279677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '383a0a6dc3e4'
down_revision = '27f5c8109729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cohort2Family')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort2Family',
    sa.Column('CohortID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('FamilyID', mysql.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['CohortID'], ['cohort.CohortID'], name='cohort2Family_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['FamilyID'], ['family.FamilyID'], name='cohort2Family_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('CohortID', 'FamilyID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
