"""Added AffectedStatus to Sample model

Revision ID: 4b98e878ce62
Revises: 76fb1a61caff
Create Date: 2020-01-28 14:09:16.059406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b98e878ce62'
down_revision = '76fb1a61caff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('AffectedStatus', sa.Enum('Affected', 'Unaffected', name='affectedstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'AffectedStatus')
    # ### end Alembic commands ###
