"""empty message

Revision ID: 59e242eb7d03
Revises: 383a0a6dc3e4
Create Date: 2019-02-20 17:06:26.447666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e242eb7d03'
down_revision = '383a0a6dc3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('ActiveCohort', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dataset', 'cohort', ['ActiveCohort'], ['CohortID'], onupdate='cascade', ondelete='restrict')
    op.add_column('sample', sa.Column('TissueType', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'TissueType')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'ActiveCohort')
    # ### end Alembic commands ###
