"""empty message

Revision ID: 76fb1a61caff
Revises: 6c71240c9976
Create Date: 2019-10-28 18:15:04.827583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fb1a61caff'
down_revision = '6c71240c9976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project2DefaultCohort',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('CohortID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CohortID'], ['cohort.CohortID'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['ProjectID'], ['project.ProjectID'], onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('ProjectID')
    )
    op.add_column('cohort', sa.Column('Obsolete', sa.Enum('Yes', 'No', name='obsoletestatus'), server_default='No', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohort', 'Obsolete')
    op.drop_table('project2DefaultCohort')
    # ### end Alembic commands ###
