"""empty message

Revision ID: 95622996b1a5
Revises: cec63be0932d
Create Date: 2019-03-06 17:33:32.565296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95622996b1a5'
down_revision = 'cec63be0932d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('ProjectName', sa.String(length=100), nullable=False),
    sa.Column('ProjectDescription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ProjectID'),
    sa.UniqueConstraint('ProjectName')
    )
    op.create_table('projects2Users',
    sa.Column('ProjectID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProjectID'], ['project.ProjectID'], onupdate='cascade', ondelete='restrict'),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], onupdate='cascade', ondelete='restrict'),
    sa.PrimaryKeyConstraint('ProjectID', 'userID')
    )
    op.add_column('cohort', sa.Column('ProjectID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cohort', 'project', ['ProjectID'], ['ProjectID'], onupdate='cascade', ondelete='restrict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cohort', type_='foreignkey')
    op.drop_column('cohort', 'ProjectID')
    op.drop_table('projects2Users')
    op.drop_table('project')
    # ### end Alembic commands ###
